update workflow

diff --git a/.github/workflows/provision_module.yaml b/.github/workflows/provision_module.yaml
--- a/.github/workflows/provision_module.yaml
+++ b/.github/workflows/provision_module.yaml
@@ -47,6 +47,7 @@ jobs:
     steps:
 
       - name: Retreive no-code module ID
+        id: get_no_code_module_id
         run: |
           echo "INFO     | Build required variables."
           tfc_api_url="https://app.terraform.io/api/v2"
@@ -76,6 +77,7 @@ jobs:
           fi
 
       - name: Retreive HCP Terraform Project ID
+        id: get_project_id
         run: |
           echo "INFO     | Build required variables."
           tfc_api_url="https://app.terraform.io/api/v2"
@@ -108,15 +110,31 @@ jobs:
         env:
           PROVIDER: ${{ github.event.inputs.provider }}
           NAME: ${{ github.event.inputs.name }}
+          NO_CODE_ID: ${{ steps.get_no_code_module_id.outputs.NO_CODE_ID }}
+          PROJECT_ID: ${{ steps.get_project_id.outputs.PROJECT_ID }}
+          NO_CODE: ${{ github.event.inputs.no-code }}
         run: |
           echo "INFO     | Build required variables."
           tfc_api_url="https://app.terraform.io/api/v2"
           auth_header="Authorization: Bearer ${TFC_API_TOKEN}"
           content_header="Content-Type: application/vnd.api+json"
           workspace_name="terraform-${PROVIDER}-${NAME}"
-          echo "INFO     | Creating workspace ${workspace_name} in organization ${TFC_ORGANIZATION}."
-          json_string='{"data":{"type":"workspaces","attributes":{"name":"'"${workspace_name}"'","auto_apply":true},"relationships":{"project":{"data":{"id":"prj-BYpph2TYRdFuifvr","type":"project"}},"vars":{"data":[{"type":"vars","attributes":{"key":"module_name","value":"'"${NAME}"'","category":"terraform"}},{"type":"vars","attributes":{"key":"module_provider","value":"'"${PROVIDER}"'","category":"terraform"}}]}}}}'
+          echo "INFO     | Creating workspace ${workspace_name} in project ${TFC_PROJECT}."
+          if [ "${NO_CODE}" = true ] ; then
+            no_code='{"type":"vars","attributes":{"key":"no_code_module","value":"true","category":"terraform"}}'
+          else
+            no_code='{"type":"vars","attributes":{"key":"no_code_module","value":"false","category":"terraform"}}'
+          fi
+          json_string='{"data":{"type":"workspaces","attributes":{"name":"'"${workspace_name}"'","auto_apply":true},"relationships":{"project":{"data":{"id":"'"${PROJECT_ID}"'","type":"project"}},"vars":{"data":[{"type":"vars","attributes":{"key":"module_name","value":"'"${NAME}"'","category":"terraform"}},{"type":"vars","attributes":{"key":"module_provider","value":"'"${PROVIDER}"'","category":"terraform"}},'"${no_code}"']}}}}'
           json_payload=$(echo "${json_string}" | jq)
           echo "$json_payload"
-          # curl --request POST --url "${tfc_api_url}/no-code-modules/nocode-C8CZ8RCAFuvAWtMu/workspaces" \
-          # --header "${auth_header}" --header "${content_header}" --data "${json_payload}"
+          run=(curl -sS --request POST --url "${tfc_api_url}/no-code-modules/$NO_CODE_ID}/workspaces" \
+          --header "${auth_header}" --header "${content_header}" --data "${json_payload}")
+          if ! [[ "${run}" =~ "{\"data\":" ]]; then
+            echo "ERROR    | Unable to create workspace."
+            echo "${run}"
+            exit 1
+          else
+            echo "INFO     | Workspace created successfully."
+            echo "${run}"
+          fi
